export const routes = {
  home: '/',
  dashboard: '/dashboard',
  myPets: '/my-pets',
  exploreLostPets: '/explore-lost-pets',
  reportLostPet: '/report-lost-pet',
  reportFoundPet: '/report-found-pet',
  petDetails: '/pet-details',
  editPet: '/edit-pet',
  editUser: '/edit-user',
  resetPassword: '/reset-password',
  logIn: '/log-in',
  signUp: '/sign-up',
  logout: '/logout',
}
